// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCveIrVSbTeULCdI0kbqtnqFaI_QV13uL0',
    appId: '1:998214942076:web:af1a45c1944b91f4fab8f9',
    messagingSenderId: '998214942076',
    projectId: 'canchaya-8ccdb',
    authDomain: 'canchaya-8ccdb.firebaseapp.com',
    storageBucket: 'canchaya-8ccdb.firebasestorage.app',
    measurementId: 'G-HMENWZWJTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3KicaYt6oWNlwUj0FthZKQ9qkCxNvECQ',
    appId: '1:998214942076:android:e9f38cc29dbd0f59fab8f9',
    messagingSenderId: '998214942076',
    projectId: 'canchaya-8ccdb',
    storageBucket: 'canchaya-8ccdb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgYjvOBRyJOCmpwMk9l-6jUd_ttFCTsFc',
    appId: '1:998214942076:ios:c0050e57ed9cfabbfab8f9',
    messagingSenderId: '998214942076',
    projectId: 'canchaya-8ccdb',
    storageBucket: 'canchaya-8ccdb.firebasestorage.app',
    iosBundleId: 'com.canchaya.canchaYa',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgYjvOBRyJOCmpwMk9l-6jUd_ttFCTsFc',
    appId: '1:998214942076:ios:c0050e57ed9cfabbfab8f9',
    messagingSenderId: '998214942076',
    projectId: 'canchaya-8ccdb',
    storageBucket: 'canchaya-8ccdb.firebasestorage.app',
    iosBundleId: 'com.canchaya.canchaYa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCveIrVSbTeULCdI0kbqtnqFaI_QV13uL0',
    appId: '1:998214942076:web:7439930b3f5c2e79fab8f9',
    messagingSenderId: '998214942076',
    projectId: 'canchaya-8ccdb',
    authDomain: 'canchaya-8ccdb.firebaseapp.com',
    storageBucket: 'canchaya-8ccdb.firebasestorage.app',
    measurementId: 'G-7EKTQ41T5J',
  );
}
